import type { Metadata } from "next";

import { Inter as FontSans } from "next/font/google";

import { SessionProvider } from "next-auth/react";

import { auth } from "@/auth";
import { cn } from "@/lib/utils";
import ReactQueryProvider from "@/lib/query-client";

import "./globals.css";

const fontSans = FontSans({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body
        className={cn("bg-background font-sans antialiased", fontSans.variable)}
      >
        <div className="container min-h-screen">
          <SessionProvider session={session}>
            <ReactQueryProvider>{children}</ReactQueryProvider>
          </SessionProvider>
        </div>
      </body>
    </html>
  );
}
